name: Supper-Linters

on: push

jobs:
  supper-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v2
     
      - name: Run Supper-Linters
        uses: github/supperlinter@v1
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
