name: Supper-Linter

on: push

Jobs:
  super-lint:
    name: Lint code base
    runs-on: ubunto-lates
    steps:
      - name: check code
        uses: action/checkout@v2
     
      - name: Run Supper-Linter
        user: github/supper-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
